# Generated by Django 4.1 on 2022-08-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_manager', '0002_remove_purchaseorder_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='description',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
