# Generated by Django 4.1 on 2022-08-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_manager', '0003_purchaseorder_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='description',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='amount',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
