# Generated by Django 4.1 on 2022-08-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_manager', '0005_purchaseorder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='end_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
