# Generated by Django 4.1 on 2022-08-31 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0001_initial'),
        ('po_manager', '0006_purchaseorder_end_date_purchaseorder_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='company_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company_manager.company'),
            preserve_default=False,
        ),
    ]
